### ISSUE TITLE
[tests] add a mock gist-api to remote-proofs

### ISSUE THREAD

**Issue by daviddahl** [IBM/ipfs-social-proof#43]
This way we can not test the network connectivity live in the test and we will avoid false test failures over weird async behavior.

**Comment by daviddahl** [comment]
See: https://github.com/IBM/ipfs-social-proof/blob/master/test/remote-proofs.spec.js#L134
and: https://github.com/IBM/ipfs-social-proof/blob/master/src/remote-proofs.js#L19

Inside `remote-proofs.js` one will need to make the gist-client configurable or just set it manually in the test file

**Comment by cdeng001** [comment]
You mentioned moving mocks to their own space. I think there should be a dir for mocks, like this and ipfs node mocks, that can be built upon as we add tests.

**Comment by daviddahl** [comment]
this is a dupe of #50
