### ISSUE TITLE
[API] test and make sure API operates in node.js and browser

### ISSUE THREAD

**Issue by daviddahl** [IBM/ipfs-social-proof#6]

**Comment by cdeng001** [comment]
Thinking E2E with jsdom.

**Comment by daviddahl** [comment]
jsdom is for unit tests - an e2e test suite would start the node server and use something like puppeteer to instrument the applications UI.

**Comment by daviddahl** [comment]
This is actually now working - I think all of the API is working in node and client - apart from the async-ish bug in remote-proofs while running mocha node tests
